#!/bin/bash

COMMON_PACKAGES="zsh"

if [[ "$OSTYPE" == "darwin"* ]]; then
  PACKAGES="${COMMON_PACKAGES} ssh 1pw iterm2"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  PACKAGES="${COMMON_PACKAGES}"
else
  fail "Unsupported OS"
fi

stow --no-folding -t ~ -d "$(dirname $(realpath $0))" $PACKAGES
